#!/bin/bash
echo ""
echo "********************"
echo "*  Housekeeping!!! *"
echo "********************"
echo ""
sudo apt update
sudo apt upgrade
sudo apt autoremove
sudo flatpak update
echo ""
echo "***********************"
echo "*  Fresh and clean :) *"
echo "***********************"
echo ""
