#!/bin/bash
echo ""
echo "********************"
echo "*  Housekeeping!!! *"
echo "********************"
echo ""
sudo apt update -y
sudo apt upgrade -y
sudo apt autoremove -y
flatpak update -y
echo ""
echo "***********************"
echo "*  Fresh and clean :) *"
echo "***********************"
echo ""
